name: Build & publish Docker image

on:
    workflow_dispatch:
    push:
        tags: [ v* ]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }} 

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3.0.0

            - name: Log in to registry ${{ env.REGISTRY }}
              uses: docker/login-action@v3.0.0
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Calculate Docker tags
              id: calc_tags
              run: |
                DOCKER_TAGS="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
                if [[ "${{ github.event_name }}" == "push" && "${{ startsWith(github.ref, 'refs/tags/v') }}" == "true" ]]; then
                  DOCKER_TAGS="${DOCKER_TAGS},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}"
                fi
                echo "DOCKER_TAGS=${DOCKER_TAGS}"
                echo "DOCKER_TAGS=${DOCKER_TAGS}" >> $GITHUB_ENV
                echo "::set-output name=DOCKER_TAGS::${DOCKER_TAGS}"
              env:
                REGISTRY: ${{ env.REGISTRY }}
                IMAGE_NAME: ${{ env.IMAGE_NAME }}
              shell: bash
              

            - name: Build and push Docker image
              id: build-and-push
              uses: docker/build-push-action@v5.0.0
              with:
                context: .
                push: true
                provenance: false
                tags: ${{ steps.calc_tags.outputs.DOCKER_TAGS }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
            